####################
# 1. 构建与发布目录
####################
[build]
  command = "npm run build"   # 对应 package.json -> "build": "tsc && vite build"
  publish = "dist"            # vite 默认输出目录
  functions = "netlify/functions"  # Netlify 函数目录

####################
# 2. 环境变量
####################
# 注意：敏感数据如API密钥不应直接在此文件中设置
# 而应在Netlify的部署设置中进行配置
[build.environment]
  NODE_VERSION = "18"

####################
# 3. 运行时路由规则
####################

# 3-A 代理 Netlify 函数
[[redirects]]
  from = "/api/v1/generate"
  to = "/.netlify/functions/generate"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/generate/:id"
  to = "/.netlify/functions/get-generation/:id"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/generate/extend"
  to = "/.netlify/functions/extend"
  status = 200
  force = true

# 3-B 备用代理（如果需要直接访问外部API）
[[redirects]]
  from = "/api/*"
  to = "https://apibox.erweima.ai/api/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

# 3-C SPA 二级路由回退
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

####################
# 4. 附加 headers
####################
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://apibox.erweima.ai; media-src 'self' https://*.amazonaws.com;"
    Cache-Control = "public, max-age=300, s-maxage=600"
